sudo: required
services:
- docker
branches:
  only:
  - master
before_install:
- docker-compose build
- docker-compose run -e MIX_ENV=test designator mix deps.get
script:
- docker-compose run -e MIX_ENV=test designator mix test