version: '2'

services:
  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=designator"
      - "POSTGRES_PASSWORD=designator"

  web:
    build: ./
    image: zooniverse/designator
    volumes:
      - ./:/app
      - build_cache:/app/_build
    ports:
      - "4000:4000"
    environment:
      - "MIX_ENV=dev"
      - "POSTGRES_USER=designator"
      - "POSTGRES_PASS=designator"
      - "POSTGRES_HOST=pg"
      - "SECRET_KEY_BASE=secret"
    links:
      - postgres:pg

  test:
    image: zooniverse/designator
    volumes:
      - ./:/app
      - build_cache:/app/_build
    environment:
      - "MIX_ENV=test"
      - "POSTGRES_USER=designator"
      - "POSTGRES_PASS=designator"
      - "POSTGRES_HOST=pg"
      - "DESIGNATOR_AUTH_USERNAME=username"
      - "DESIGNATOR_AUTH_PASSWORD=password"
    links:
      - postgres:pg

volumes:
    build_cache:
